### ISSUE TITLE
Getting a exception thrown

### ISSUE THREAD

**Issue by anthr76** [theriley106/SneakerBotTutorials#11]
AttributeError: 'dict' object has no attribute 'replace'

**Comment by scyzemic** [comment]
looks like the issue is [this line](https://github.com/theriley106/SneakerBotTutorials/blob/master/main.py#L63) in main.py for the case where `proxy = None`, this is my first time looking at python, so I'm not sure how to go about a fix for a PR

**Comment by scyzemic** [comment]
Looks like this was fixed on last change pushed to master

**Comment by theriley106** [comment]
@anthr76 Sorry about that.  I pushed a change without testing it fully.  Should be fixed now.
